version: '3.8'

services:
  warehouse:
    build: .
    ports:
      - "${WEBHOOK_PORT}:${WEBHOOK_PORT}"
    environment:
      - MODULE_NAME=main
      - VARIABLE_NAME=app
      - WEBHOOK_PORT=${WEBHOOK_PORT}
      - WEBHOOK_HOST=${WEBHOOK_HOST}
      - ENVIRONMENT=${ENVIRONMENT}
      - KAFKA_TOPICS=${KAFKA_TOPICS}
    env_file:
      - .env